/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.spring.io/libs-snapshot")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.springframework.data.spring.data.keyvalue)
    api(libs.com.hazelcast.hazelcast)
    api(libs.org.slf4j.slf4j.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.springframework.spring.test)
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.org.projectlombok.lombok)
    testImplementation(libs.javax.annotation.javax.annotation.api)
    testImplementation(libs.org.hamcrest.hamcrest.all)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.springframework.spring.test)
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.org.projectlombok.lombok)
}

group = "com.hazelcast"
version = "2.4.1-SNAPSHOT"
description = "Spring Data Hazelcast"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
